### ISSUE TITLE
Software Serial read not proper

### ISSUE THREAD

**Issue by bimalpaneru** [paulvha/apollo3#6]
Using RS485 with software serial at 19200

Sending 0xAA being received as 0xD5.

Pulses on oscilloscope are fine.

Sender:
MicroMod (rx = G4, tx = G1)

Receiver:
RedBoard(rx =D2, tx = D5)

**Comment by paulvha** [comment]
just tested with 2 micromod's. 

Get the same problem. working on a better way to handle but for now in SoftwareSerial.cpp, change line 214 the comp  = 18 to comp = 9
regards,
Paul

**Comment by bimalpaneru** [comment]
Thank you for the help. Appreciate it mate!

**Comment by paulvha** [comment]
I have spent a lot of time today on this issue, but have not come to a conclusion yet. Sharing some findings : 
in the original tests, I used an Artemis EDGE to set the compensation. I thought this compensation was only needed because of the time to execute the code and IRQ. Turned out that every board has components that impact this as well. These components are within specification but may be on the edge.  Hence better fine tune is needed for each and every board. Especially when it gets to 38400. That is where my challenge still is.
 
I created a separate sketch and changes to the SoftwareSerial library to determine the right compensation for a specific board. One can then overrule the default compensation to get better results.  It is interesting to see how that differs board to board, while these boards all have an Artemis / Apollo3 processor.

hopefully more after the weekend.

**Comment by paulvha** [comment]
I have created an updated version for SoftwareSerial. It has a new example8 to set the compensation for the speed (if needed).
The max sending speed is 38400 and the max RX speed is still 19200 (stable), but 38400 COULD be possible if you are lucky.

regards,
Paul

**Comment by bimalpaneru** [comment]
Thanks Paul 
Much appreciated

**Comment by bimalpaneru** [comment]
Might be useful to others, `SoftwareSerial` instance needs to be re initialised using `.begin()` after MCU wakes up from a sleep.

**Comment by paulvha** [comment]
yes. Same as with Serial, one should call **mySerial.end()** before going to sleep and **mySerial.begin()** after waking up. In .end() it will remove the interrupt from the RX-pin. I'll add something in the readme file
